version: "3.7"
services:
  frp:
    build: .
    image: d2x3/frps:1.0.0
    ports:
     - "80:80"
     - "7000:7000"
     - "7500:7500"
     - "443:443"
    volumes:
     - type: bind
       source: ./frps.ini
       target: /frps/frps.ini
    restart: always
